node {

            stage('Build') {
                    echo 'SCM....'
                    //git credentialsId: 'ning.liu4@hpe.com', url: 'https://github.houston.entsvcs.net/ServiceAgent/aspnetcore-docker-cross-linux-wins.git'

                    echo 'Building....'

                   //bat '"C:\\Program Files\\Git\\usr\\bin\\ssh.exe" liuning0820@13.75.117.74 mv *.* /mnt/DockerDemoASPNetCore/ '
                    

                }
   
            stage('Test') {
                echo 'Testing....'
            }
            stage('Deploy') {
                echo 'Deploying....'
            }

}