node {
      try{
            stage('Prep')
            {
                        
            }
            stage('Build') {
                    echo 'SCM....'
                    git credentialsId: 'tom.halpin@dxc.com', url: 'https://github.com/tom-halpin/AnsibleCICD'

                    echo 'Building....'
                }
   
            stage('Ansible Lint') {
                echo 'Running ansible-lint ...'
                //command to run ansible-lint the parameter required is the path where the playbooks are stored
                sh 'ansible-lint ansible'
            }
            stage ("Molecule Lint") {
               echo 'Running Molecule Lint ...'
                  sh 'molecule lint'
        }
            stage('Deploy') {
                echo 'Deploying....'
            }
    } catch(all) {
        currentBuild.result = "FAILURE"
        throw err
    }
}
